### ISSUE TITLE
Removing sticker packs

### ISSUE THREAD

**Issue by Jeirs** [awaken1ng/bd-linestickers#1]
Is there a string I can type into the console to remove a certain pack of sticker?

I double-pasted a string twice and there are two sticker packs of the same type.

**Comment by Kamil118** [comment]
I know I am few moths too late but I will just post it here in case anyone needed it; this command deletes >first< sticker pack, so, unfortunately, you will have to readd all your sticker packs
lineemotes.deletePack()
