### ISSUE TITLE
Menu size is wrong !

### ISSUE THREAD

**Issue by ghost** [awaken1ng/bd-linestickers#11]
![screenshot 54](https://user-images.githubusercontent.com/29485602/27261072-508e199e-5459-11e7-8beb-d5d318afb9b6.png)
with the new update for Better Discord its sticker selection menu has different size

**Comment by awaken1ng** [comment]
Whoops, I forgot to set the default menu size, open the console (Ctrl + Shift + I, Console tab) and execute `lineemotes.menu.setSize(344, 326)` to fix it, adjust the values if you want to

**Comment by awaken1ng** [comment]
I've updated the plugin to have a proper default size check, _should_ not break like this anymore, if you happen to come across any other obvious stuff I've missed, please do inform me.
