### ISSUE TITLE
No Emoji Tab

### ISSUE THREAD

**Issue by crse** [awaken1ng/bd-linestickers#12]
The tab supposed to be showing emoji tab like this 
http://i.imgur.com/o4OT4E8.png

but it doesn't showing emoji tab.
http://i.imgur.com/yg0G8eA.png

**Comment by awaken1ng** [comment]
Make sure that the Discord emoji menu is enabled in BD settings

![](https://camo.githubusercontent.com/eae78b6da2536a0fed48f8120da51e47733511ac/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3330363032303830333534363434373837322f3333393032343137343637383830323433332f756e6b6e6f776e2e706e67)
