### ISSUE TITLE
Why is this a virus?

### ISSUE THREAD

**Issue by nate101pro** [awaken1ng/bd-linestickers#13]
Windows defender ,the only antivirus program that works without stabbing you in the back, says theirs a Trojan in this download, Threat level: Severe
This completely denies any possible way to download this and probably means this download is vary bad.

This is where it sends me, 
[Trojan:JS/Jorv.A!cl](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:JS/Jorv.A!cl)

**Comment by awaken1ng** [comment]
A false positive or something else infecting the file. I didn't put any malicious code as far as I remember. [VirusTotal](https://www.virustotal.com/#/url/665fa757d1911c9995efc7d5b1958739696a2f088336dabf25c275bbda748d1f/detection) also reports only 1 false positive.
