### ISSUE TITLE
Unable to find ID

### ISSUE THREAD

**Issue by Night-wing** [awaken1ng/bd-linestickers#17]
I'm unable to find the ID of the line stikers, im sharing a picture regarding the issue

https://imgur.com/a/At6vH

**Comment by awaken1ng** [comment]
Whoops, looks like LINE slightly changed their sticker URLs, updated the script at [greasyfork](https://greasyfork.org/en/scripts/23630), should work now, thank you for the report.

**Comment by Night-wing** [comment]
Thanks a lot for the quick response, its working now
