### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by xerance** [awaken1ng/bd-linestickers#19]
when I click on any stickers(after I added them correctly) it just writes undefined in the chat field, like this https://puu.sh/APLZx/587b6ad437.png

**Comment by awaken1ng** [comment]
It does, just got broken by new class normalization feature (that was added somewhat recently to Zerebos's BD) since I was using a very daft way to check if sticker/emote element has the right class.
Download an update with the fix or disable the normalization in BD settings.
