### ISSUE TITLE
Script no longer working with latest version of Tampermonkey

### ISSUE THREAD

**Issue by Night-wing** [awaken1ng/bd-linestickers#20]
It appears to be that whenever i want to add a new set of Line stickers, the ID of them are missing?

I'm sharing a new screenshot regarding this issue
![Screenshot_166](https://user-images.githubusercontent.com/9482201/56171428-ddb1b200-5faa-11e9-803e-53f79b0cae30.png)

**Comment by awaken1ng** [comment]
Looks like the classes were changed, I've updated the script, should work now

**Comment by Night-wing** [comment]
Thank you for your response, I got the script updated and its working now.
