### ISSUE TITLE
Bad Size? Bad Position?

### ISSUE THREAD

**Issue by fluffyloopy** [awaken1ng/bd-linestickers#21]
![Screenshot (22)](https://user-images.githubusercontent.com/36381994/59466042-bc076680-8e45-11e9-9cda-10ecf5c5baa2.png)

why does this happen?

**Comment by awaken1ng** [comment]
Seeing as you have a theme on, highly likely it's caused by that, you'll need to apply some custom CSS to fix the menu.
If it's still borked without the theme and custom CSS, then one of the Discord updates is the cause.

**Comment by fluffyloopy** [comment]
oof. it works after i removed everything
