### ISSUE TITLE
Corrupted sticker pack

### ISSUE THREAD

**Issue by Kamil118** [awaken1ng/bd-linestickers#3]
This sticker pack is corrupted after using console command to get all data https://store.line.me/stickershop/product/1276009/en
i get this command: lineemotes.appendPack("Sarcastic girl with pigtails", 1276009, 11187954, 1, 40)
http://puu.sh/uYO3k/d63c7da09d.png

**Comment by awaken1ng** [comment]
URL for stickers changed at some point, probably the reason, hopefully fixed in 0.6
