### ISSUE TITLE
Url

### ISSUE THREAD

**Issue by ApinkBomi** [awaken1ng/bd-linestickers#9]
Is there a way to get rid of the URL and just have the image?

**Comment by awaken1ng** [comment]
The plugin should hide the URL on the client side,
to fully hide it I'd need to upload the sticker instead, which proves to be a little difficult to execute, even if I'll get to the internal upload function, I'm still not sure how to upload the sticker, I suppose my only hope would be to somehow pinpoint the file in cache and point that to upload function.

tl;dr it's hard, if not impossible, to implement

**Comment by ApinkBomi** [comment]
![98bcbe2848bdc335a85813dd56b7605c](https://user-images.githubusercontent.com/29315122/26999156-c45c4814-4d47-11e7-8a2f-7fda4dfe1d37.png)

So I can't hide this URL? Just Checking

**Comment by awaken1ng** [comment]
Is that the screenshot on your side with a plugin or someone without a plugin?

In first case you can hide the URL just for yourself, the others without a plugin will still see it, but you won't.
Don't remember it's default value if I set any, in case it's not on by default you can open developer tools with `Ctrl + Shift + I`, head to the console and paste the following command `bdPluginStorage.set(lineemotes.storage.getName(), 'hideURLs', true)`, then either reload Discord or go to settings and disable then enable the plugin back. 
If you're still seeing the links, switch the text channel or a server to let the observer do it's work and hide the URL. (If you reloaded Discord, don't forget to let BD initialize).

_I really should add this to the options menu, shouldn't I_

**Comment by awaken1ng** [comment]
I've added the option to toggle URL hide in the settings
